name: Update README with Badge
on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Badge Data
        run: |
          curl -s https://tryhackme.com/api/v2/badges/public-profile?userPublicId=1448937 > badge.json
          echo "![TryHackMe Badge](https://tryhackme.com/api/badges/userPublicId/1448937.png)" > README.md

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update badge"
          git push
